serviceMonitor:
  enabled: true
# prometheusRule:
#   enabled: true
dashboards:
  enabled: true

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File /fluent-bit/etc/parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            cri
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     64MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        # Kube_URL            https://kubernetes.default.svc:443
        # Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        # Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Annotations         Off
        Labels              On
    # [FILTER]
    #     Name                nest
    #     Match               kube.*
    #     Operation           lift
    #     Nested_under        kubernetes
    #     Add_prefix          kubernetes_
    # [FILTER]
    #     Name                nest
    #     Match               kube.*
    #     Operation           lift
    #     Nested_under        kubernetes_labels
    #     Add_prefix          kubernetes_labels_
    # [FILTER]
    #     Name                grep
    #     Match               kube.*
    #     Exclude             log_processed['status'] /^(?:101|200|201|202|204|301|302)/
  outputs: |
    [OUTPUT]
        Name loki
        match *
        host loki-gateway.default.svc.cluster.local
        port 80
        label_keys $sub['stream']
        auto_kubernetes_labels on

    # [OUTPUT]
    #     Name stdout
    #     Match *
