prometheus:
  enabled: true

grafana:
  adminPassword: "admin" # Change to a more secure password
  forceDeployDatasources: true
  forceDeployDashboards: true
  defaultDashboardsEnabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.default.svc.cluster.local/
    - name: Tempo
      type: tempo
      url: http://tempo.tempo.svc.cluster.local:3100
  plugins:
    - grafana-lokiexplore-app
